Ease locking to speedup ingestion on startup
timescale/promscale pull request #1016
Opened 2022-01-06 12:37 UTC by niksajakovljevic

Due to a lot of locking while inserting metadata on series we tend to
have a `slow start`. It can take up to 15-20 minutes to get to full speed
when ingesting heavily (eg. 500K/s).
Trying to ease some locking.

SQL function `get_or_create_series_id_for_label_array` was taking unnecessary
ACCESS SHARE lock on metric data table. The label keys are actually
created in another function so no need to take this lock.

SQL function `get_new_pos_for_key` was taking SHARE UPDATE EXCLUSIVE lock
on metric data table. Using advisory lock here should enable writes to metric
data table while we safely get new key position.

2022-01-06 18:21 UTC, cevian requested changes
I'd rather get all the changes in `SCHEMA_CATALOG.get_or_create_series_id_for_label_array` in first as a separate PR because the changes there are obvious and then move on to the new_pos_for_key changes that seem less obvious to me.

2022-01-06 18:21 UTC, cevian commented on pkg/migrations/sql/idempotent/base.sql
>     SELECT mtn.id, mtn.table_name FROM SCHEMA_CATALOG.get_or_create_metric_table_name(metric_name) mtn
we can also delete this line right?

2022-03-30 01:30 UTC, cevian commented
@niksajakovljevic can this PR be closed?

2022-11-29 09:51 UTC, niksajakovljevic commented
Since SQL logic was moved to extension repository this PR can be closed.

2022-11-29 09:51 UTC, closed without merging