Fix skipping compression of last closed chunk
timescale/promscale pull request #1081
Opened 2022-01-26 07:57 UTC by antekresic

## Description

Due to a bug in logic, we were skipping compression of the last
chunk which ended over an hour ago from current time. This was
causing to have one more chunk per metric uncompressed, causing
us to use more storage than necessary.

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [x] CHANGELOG entry for user-facing changes
- [ ] ~~Updated the relevant documentation~~

2022-01-26 13:56 UTC, JamesGuthrie requested changes
It seems as though we have good coverage for the compression tests. Could you update the existing tests to prevent a regression?

2022-01-26 14:43 UTC, jgpruitt approved these changes

2022-01-26 15:25 UTC, cevian approved these changes
Good catch!

2022-01-27 07:55 UTC, JamesGuthrie approved these changes
LGTM!

2022-01-27 10:32 UTC, merged