New migration logic to use extension
timescale/promscale pull request #1110
Opened 2022-02-04 17:15 UTC by jgpruitt

## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue._

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

2022-02-07 10:46 UTC, JamesGuthrie reviewed
Looks good from a high-level point of view. I need to take another look when I have a bit more mental capacity.

2022-02-07 16:25 UTC, jgpruitt commented on pkg/pgmodel/migrate.go
> +		extOptions.Install = true // TODO decide whether it is appropriate to force this to true
I like this idea.

2022-02-07 20:11 UTC, jgpruitt commented on pkg/pgmodel/migrate.go
> +		extOptions.Install = true // TODO decide whether it is appropriate to force this to true
wait. why would we introduce AND deprecate `-startup.{install,upgrade}-promscale-extension` in the same release? or am I confused?

2022-02-08 23:44 UTC, cevian requested changes
Biggest question is do we need this merged before the new migration change? I think if we don't then we can simplify the logic here quite a bit.

2022-02-08 23:44 UTC, cevian commented on pkg/pgmodel/common/extension/extension.go
>  		if err == errors.ErrExtUnavailable {
This should be deleted right? The extension is now mandatory.

2022-02-08 23:44 UTC, cevian commented on pkg/pgmodel/common/extension/extension.go
> +func CheckVersions(conn *pgx.Conn, migrationFailedDueToLockError bool, allowPreRelease bool) error {
Why this change in API all over the place?

2022-02-08 23:44 UTC, cevian commented on pkg/pgmodel/common/extension/extension.go
>  		ExtensionIsInstalled = false
we should remove this global if possible. The extension is now mandatory...

2022-02-08 23:44 UTC, cevian commented on pkg/pgmodel/migrate.go
> +	if appSemver.LT(firstAppVersionWithNewMigration) {
do we really need this branch? Will we merge this PR before we are ready to release the new migration system? If not, then why keep this branch around?

2022-02-08 23:44 UTC, cevian commented on pkg/pgmodel/common/extension/extension.go
>  		if err == errors.ErrExtUnavailable {
Also need to change line 165 below too

2022-02-08 23:44 UTC, cevian commented on pkg/pgmodel/migrate.go
> +	appSemver := semver.MustParse(appVersion.Version)
I think we should be a bit conservative here and double check the extension we need is first available before doing any of this migration logic. Something like
```
_, _, err := extensionVersions(conn, "promscale", version.ExtVersionRange, version.ExtVersionRangeString, extOptions)
// check for err. If there is an err that means that the right extension version is unavailable
```

2022-02-08 23:44 UTC, cevian commented on pkg/pgmodel/old_migrator.go
> +// This file and its contents are licensed under the Apache License 2.0.
is this the old system verbatim or were there any logic changes. Hard to tell from this diff

2022-02-08 23:44 UTC, cevian commented on pkg/runner/flags.go
> +	fs.BoolVar(&cfg.InstallTimescaleDBExtension, "startup.install-timescaledb-extension", true, "Install TimescaleDB extension.")
is `startup.install-extension.timescaledb` a better name? WDYT?

2022-02-09 19:49 UTC, closed without merging

2022-02-09 19:50 UTC, jgpruitt commented
moving to new PR and branch https://github.com/timescale/promscale/pull/1132