Fix ingested_samples_total telemetry
timescale/promscale pull request #1165
Opened 2022-02-17 14:45 UTC by Harkishen-Singh

Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

## Description

This PR fixes ingested_samples telemetry by using another metric name for items (aka insertables) received.

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

2022-02-17 15:02 UTC, niksajakovljevic requested changes
Hmmm...This doesn't seem to be inline with `IngestorItems` being items that we've received and `IngestorInsertablesIngested` being items that we've inserted into DB. Let's discuss this again so we are all on the same page.

2022-02-17 15:05 UTC, niksajakovljevic commented on pkg/api/write.go
> +	callBack func(code string, duration float64, received, ingested items),
Consider naming this function to something more specific :)

2022-02-17 16:10 UTC, niksajakovljevic commented on pkg/pgmodel/ingestor/copier.go
> -	metrics.IngestorInsertablesIngested.With(prometheus.Labels{"type": "metric", "kind": "sample"}).Add(float64(totalSamples))
I'd rather update metrics in the same place where ingest happens than via callbacks ( unless there is a special reason). Mostly for keeping things simple

2022-02-18 09:01 UTC, niksajakovljevic approved these changes

2022-02-21 12:48 UTC, antekresic approved these changes
lgtm

2022-02-22 11:04 UTC, merged