Improve logging of active servers on start.
timescale/promscale pull request #1217
Opened 2022-03-03 07:57 UTC by Harkishen-Singh

Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

## Description

This PR improves the logging of Promscale on start. Fixes: #1182 

The logs now will be
```shell
level=warn ts=2022-03-03T07:54:25.175Z caller=extension.go:59 msg="could not install promscale: the extension is not available. continuing without extension"
level=info ts=2022-03-03T07:54:25.186Z caller=client.go:146 msg="Prometheus HA is not enabled"
level=info ts=2022-03-03T07:54:25.192Z caller=client.go:116 msg="postgresql://postgres:%2A%2A%2A%2A@localhost:5432/timescale?application_name=promscale%400.11.0-dev.0&connect_timeout=60&sslmode=allow" numCopiers=8 pool_max_conns=80 pool_min_conns=8 statement_cache="512 statements"
level=warn ts=2022-03-03T07:54:25.215Z caller=telemetry.go:56 msg="Promscale collects anonymous usage telemetry data to help the Promscale team better understand and assist users. This can be disabled via the process described at https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry/#disabling-telemetry"
level=info ts=2022-03-03T07:54:25.222Z caller=runner.go:129 msg="Started Prometheus endpoint" listening-port=:9201
level=info ts=2022-03-03T07:54:25.222Z caller=runner.go:207 msg="Started OpenTelemetry OTLP GRPC server" listening-port=:9202
level=info ts=2022-03-03T07:54:25.223Z caller=runner.go:220 msg="All components are ready!"
```

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

2022-03-03 08:33 UTC, VineethReddy02 approved these changes

2022-03-03 12:32 UTC, antekresic approved these changes

2022-03-03 12:37 UTC, VineethReddy02 approved these changes

2022-03-03 13:06 UTC, niksajakovljevic requested changes

2022-03-03 13:06 UTC, niksajakovljevic commented on pkg/runner/runner.go
> +			}, func(err error) {},
When interrupt happens we need to stop grpc Server: 
```
func(err error) {grpcServer.Stop()}
```

2022-03-03 13:06 UTC, niksajakovljevic commented on pkg/runner/runner.go
> +			}, func(err error) {},
Same here as above. On interrupt we need to stop the server. Also consider naming server more intuitive eg: `openTelGrpcServer`

2022-03-03 13:07 UTC, niksajakovljevic commented on pkg/runner/runner.go
> +		}, func(err error) {},
We need to handle interrupt like in comments above.

2022-03-03 13:09 UTC, niksajakovljevic commented on pkg/runner/runner.go
> +			log.Info("msg", "Started Prometheus HTTP server", "listening-port", cfg.ListenAddr)
Since we are not starting Prometheus HTT server consider changing text to: `Started Prometheus remote storage HTTP server`

2022-03-03 13:30 UTC, niksajakovljevic commented on pkg/runner/runner.go
> +	err = group.Run()
We need to add one more group that will listen to OS interrupt signals and return when it gets one.

2022-03-04 10:39 UTC, niksajakovljevic approved these changes

2022-03-04 10:40 UTC, merged