Verify telemetry engine nil if TimescaleDB is not installed.
timescale/promscale pull request #1233
Opened 2022-03-11 10:33 UTC by Harkishen-Singh

Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

Fixes: https://github.com/timescale/o11y-team-applications/issues/145

## Description

Same as the heading.

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

2022-03-11 10:49 UTC, JamesGuthrie requested changes
Two things:

1. Tests aren't passing.
2. I also added skips to `TestTelemetrySQLStats` and `TestPromQLBasedTelemetry`. Should those not also be refactored in the same way?

2022-03-11 12:10 UTC, Harkishen-Singh commented
> TestTelemetrySQLStats

No, SQLStats is completely on SQL side of TimescaleDB so we always skip if there is no TimescaleDB. I feel the same way for `TestPromQLBasedTelemetry` as if the image is non-timescaleDB, then setting up client, router goes in vain as the next lines involve checking from database which again needs to be TImescaleDB.

2022-03-14 08:30 UTC, antekresic approved these changes

2022-03-14 12:04 UTC, JamesGuthrie approved these changes
I think it might make more sense to keep the skips there and add and explicit test which validates that the engine is null when timescaledb is not present.

2022-03-14 12:51 UTC, merged