Fix `promscale_ingest_max_sent_timestamp` value for traces.
timescale/promscale pull request #1270
Opened 2022-03-24 14:24 UTC by Harkishen-Singh

Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

Fixes: #1239

## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue._

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

2022-03-28 07:23 UTC, antekresic requested changes

2022-03-28 07:23 UTC, antekresic commented on pkg/pgmodel/ingestor/trace/writer.go
> +	metrics.IngestorMaxSentTimestamp.With(traceLabel).Set(float64(maxEndTimestamp * 1e3))
Isn't this in microseconds and we want milliseconds?

I suggest using `time.Time` for `maxEndTimestamp` and avoid these magic conversions.

2022-03-30 10:47 UTC, antekresic approved these changes

2022-03-31 08:04 UTC, niksajakovljevic commented on pkg/pgmodel/ingestor/trace/writer.go
> +				if maxEndTime.Before(end) {
To get maximum time this needs to be inversed: `maxEndTime.After(end)`

2022-03-31 08:26 UTC, niksajakovljevic approved these changes

2022-03-31 08:26 UTC, merged