Benchmark metric ingest
timescale/promscale pull request #1279
Opened 2022-04-01 14:27 UTC by niksajakovljevic

Read Prometheus data files and generate ingest load.
Using native Prometheus data format makes is easy to swap input data
which can be handy when debugging ingest performance.

2022-05-30 07:16 UTC, paulfantom reviewed
I did a quick review pass of this and got few minor issues:
- there are some issues with library imports
- Could we use git-lfs to store binary file (prometheus-data.tar.gz)?

2022-05-30 07:16 UTC, paulfantom commented on pkg/tests/testsupport/metric_loader.go
> +	log.Info("loading blocks, total samples", it.blocks[it.curBlockIdx].Meta().Stats.NumSamples, "series", it.blocks[it.curBlockIdx].Meta().Stats.NumSeries)
```suggestion
	log.Infof("loading blocks, total samples: %v, series: %v",
			it.blocks[it.curBlockIdx].Meta().Stats.NumSamples,
			it.blocks[it.curBlockIdx].Meta().Stats.NumSeries)
```
nit: a bit easier to read in code review view.

2022-06-06 10:59 UTC, antekresic commented on pkg/tests/testsupport/metric_loader.go
> +			log.Error(err)
```suggestion
			log.Error("err", err)
```

2022-06-06 10:59 UTC, antekresic commented on pkg/tests/testsupport/metric_loader.go
> +		wg.Add(1)
This line should go before goroutine. Its idiomatic to show the goroutine which will be responsible for sending the done signal.

2022-06-06 10:59 UTC, antekresic commented on pkg/tests/testsupport/metric_loader.go
> +	if sampleRate != 0 {
We could use `rate.Inf` for `sampleRate == 0`. Would simplify the rate limiting logic (no need for checking nils).

2022-06-06 12:06 UTC, Harkishen-Singh requested changes
I think we should redesign the PR to have something like a routine sending a batch that contains 1 sample from all series. This will mimic and actual prometheus remote-write, and keep the single iteration of go bench quick.

2022-06-06 12:06 UTC, Harkishen-Singh commented on pkg/tests/testsupport/metric_loader.go
> +		XXX_sizecache:        0,
we can remove these

2022-06-06 12:06 UTC, Harkishen-Singh commented on pkg/tests/testsupport/metric_loader.go
> +			for sample := range si.shards[shard] {
```suggestion
			for ts := range si.shards[shard] {
```
`sample` name is very confusing. This is samples + series, which is proper ts

2022-06-06 13:39 UTC, niksajakovljevic commented
> I think we should redesign the PR to have something like a routine sending a batch that contains 1 sample from all series. This will mimic and actual prometheus remote-write, and keep the single iteration of go bench quick.

@Harkishen-Singh I am not sure I follow. Batch size of Prometheus is configurable and so is here. I also didn't get the part about quick bench iteration. Here we run benchmark with 1.5M samples and this data set can be replaced or we can add additional datasets each with different `shape`. Let's discuss more offline.

2022-06-06 15:17 UTC, niksajakovljevic commented on pkg/tests/end_to_end_tests/metric_ingest_bench_test.go
> +		}
That's not the same code. I guess you meant: `for it.Next() && sampleCounter < 10`

2022-06-07 08:53 UTC, Harkishen-Singh approved these changes

2022-06-07 08:53 UTC, Harkishen-Singh commented on pkg/tests/end_to_end_tests/metric_ingest_bench_test.go
> +	withDB(b, "bench_metric_ingest", func(db *pgxpool.Pool, t testing.TB) {
```suggestion
	withDB(b, "bench_e2e_metric_ingest", func(db *pgxpool.Pool, t testing.TB) {
```
Let's be explicit that this benchmark is e2e.

2022-06-07 10:05 UTC, antekresic approved these changes
:tada:

2022-06-07 10:05 UTC, antekresic commented on pkg/tests/testsupport/metric_loader.go
> +	if sampleRate != 0 {
Have you benchmarked this? :grin:

2022-06-07 12:17 UTC, merged