deploy/helm-chart: remove openTelemetry.enabled option
timescale/promscale pull request #1290
Opened 2022-04-11 13:35 UTC by paulfantom

Signed-off-by: Paweł Krupa (paulfantom) <pawel@krupa.net.pl>

## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue._

As in title. Fixes https://github.com/timescale/promscale/issues/1241

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [x] CHANGELOG entry for user-facing changes
- [x] Updated the relevant documentation

2022-04-11 13:38 UTC, cevian requested changes
Wait why are we removing the option instead of changing the default from `false` to `true`. Shouldn't we still allow users to turn Otel tracing off?

2022-04-11 13:40 UTC, paulfantom commented
@cevian That's what is described in issue - https://github.com/timescale/promscale/issues/1241.

2022-04-11 13:42 UTC, paulfantom commented
Pinging @VineethReddy02 and @ramonguiu for clarification if we want to allow disabling tracing (as suggested by @cevian) or do we want to remove this option and always run with tracing enabled (as described in #1241).

2022-04-12 07:36 UTC, JamesGuthrie requested changes

2022-04-12 07:36 UTC, JamesGuthrie commented on deploy/helm-chart/values.yaml
>  # so tracing features needs to be explicitly enabled.
These lines should also go.

2022-04-12 08:00 UTC, paulfantom commented on deploy/helm-chart/values.yaml
>  # so tracing features needs to be explicitly enabled.
fixed.

2022-04-12 08:06 UTC, JamesGuthrie approved these changes
LGTM, aside from the open question about whether it should still be configurable or not.

2022-04-12 08:06 UTC, JamesGuthrie commented on deploy/helm-chart/templates/deployment-promscale.yaml
> -          {{- if or (.Values.openTelemetry.enabled) (.Values.extraArgs) }}
Do we not still need the check for `.Values.extraArgs`? I assume that if there are none set, the resulting args block is empty.

2022-04-14 10:24 UTC, antekresic approved these changes
👍

2022-04-14 12:50 UTC, VineethReddy02 commented
@paulfantom Offering an option to disable tracing would be ideal as users might prefer closing the Otel port if they are not using OpenTelmetry.

2022-04-14 14:13 UTC, cevian approved these changes
Ok discussed with @VineethReddy02  and all the disabling stuff needs to be reworked almost completely anyway. So removing this option completely from the helm chart (as this PR does) is the right thing to do right now.

2022-04-14 14:13 UTC, cevian commented
To be clear: there is no need to change the PR, it should be merged as-is.

2022-04-14 16:55 UTC, VineethReddy02 approved these changes

2022-04-21 10:18 UTC, merged