Prepare for the 0.11.0-alpha release
timescale/promscale pull request #1327
Opened 2022-05-03 20:31 UTC by cevian

## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue._

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

2022-05-03 20:33 UTC, cevian commented
Note this is a testing-only release in alpha. We will NOT support upgrades from 0.11.0-alpha to 0.11.0. Upgrading to this version will drop your tracing data.

2022-05-04 07:21 UTC, paulfantom requested changes
Tests are failing due to:
```
level=error ts=2022-05-03T20:33:22.505Z caller=runner.go:116 msg="aborting startup due to error" err="migration error: error while checking for supported and available promscale extension versions: The promscale extension is not available at the right version, need version: >=0.5.0-alpha <0.5.99 and the default version is 0.5.0-alpha "
```

2022-05-04 12:51 UTC, paulfantom reviewed
helm chart changes lgtm

2022-05-04 14:07 UTC, paulfantom approved these changes

2022-05-04 18:56 UTC, merged