Docs migration
timescale/promscale pull request #1358
Opened 2022-05-13 00:33 UTC by ramonguiu

## Description

Point users to the docs site for documentation and make some updates to the content in the README

2022-05-13 09:46 UTC, paulfantom requested changes
Could you run:
```
go install -a github.com/bwplotka/mdox@latest
make docs
```

and commit changes?

2022-05-13 10:15 UTC, ramonguiu commented
> Could you run:
> 
> ```
> go install -a github.com/bwplotka/mdox@latest
> make docs
> ```

@paulfantom I get this error

````
find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
>> formatting and local/remote links
mdox fmt --soft-wraps -l --links.validate.config-file=
make: mdox: No such file or directory
make: *** [docs] Error 1
````

2022-05-13 16:49 UTC, paulfantom commented
Seems like `mdox` wasn't installed before running `make docs`. Ensure you have at least golang 1.17 and run `go install -a github.com/bwplotka/mdox@latest`. Also check if `$GOBIN` is part of your `$PATH`.

---
Side note: we might want to invest some time into figuring out better management of development tools like `mdox` across developer environments.

2022-05-16 09:50 UTC, cevian approved these changes

2022-05-16 09:50 UTC, cevian commented on README.md
> +Complete user documentation is available at https://docs.timescale.com/promscale/latest/
can we make this a link?
```suggestion
Complete user documentation is available at [https://docs.timescale.com/promscale/latest/](https://docs.timescale.com/promscale/latest/)
```

2022-05-16 09:50 UTC, cevian commented on docs/alerting.md
> +The content in this page has been moved to https://docs.timescale.com/promscale/latest/alert/
let's make all of these links as well?

2022-05-16 09:52 UTC, paulfantom approved these changes

2022-05-16 09:52 UTC, merged