Adds E2E test for alerting in Promscale.
timescale/promscale pull request #1368
Opened 2022-05-20 13:25 UTC by Harkishen-Singh

Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

This commit mimics a case of actual alerting + alertmanager.
It starts the rules-manager with a alert that is always firing.

Then, in E2E test, we start a mock alertmanager server in the `alertsReceiver()
which listens for alerts just as the alertmanager does. We send down a channel
to this server that signals whether we received an expected alert or not, which
decides the fate of the test.

All references are linked in the commit.

2022-06-09 11:26 UTC, niksajakovljevic commented on pkg/pgmodel/ingestor/dispatcher.go
> +	metricBatchers         sync.WaitGroup
I am totally confused here. Can you please explain why do we need to change batcher and disaptcher for alerting e2e tests? I'm quite against this change especially as part of this PR which imho should have nothing to do with how we do batching...

2022-06-10 10:11 UTC, niksajakovljevic commented on pkg/pgmodel/ingestor/metric_batcher.go
> -	labelArrayOID uint32) {
Ohh I see this has never been used. Good catch!

2022-06-10 10:11 UTC, niksajakovljevic approved these changes

2022-06-10 10:47 UTC, antekresic requested changes
Lets try updating the test to use httptest server and try to reduce the amount of synchronization there (I feel like it can be simplified quite a bit).

2022-06-10 10:47 UTC, antekresic commented on go.mod
> +require github.com/prometheus/alertmanager v0.24.0
Why is this not grouped together with above?

2022-06-10 10:47 UTC, antekresic commented on pkg/tests/end_to_end_tests/alerts_test.go
> +	srv := &http.Server{Addr: ":8080", Handler: mux}
Lets use httptest server here if possible.

2022-06-16 07:28 UTC, antekresic approved these changes
Approved with a question.

2022-06-16 07:28 UTC, antekresic commented on pkg/pgmodel/ingestor/dispatcher.go
> -		// the following is usually non-blocking, just a channel insert
Why is this removed?

2022-06-16 07:28 UTC, merged