Fix rule manager stop
timescale/promscale pull request #1370
Opened 2022-05-23 11:12 UTC by niksajakovljevic

We need to wait for all group actors to stop before returning. Otherwise
a race condition might happen as sub components might continue running.
We also make sure to not allow closing of already closed dispatch component.

2022-05-23 13:16 UTC, Harkishen-Singh requested changes

2022-05-23 13:16 UTC, Harkishen-Singh commented on pkg/pgmodel/ingestor/dispatcher.go
> +		return fmt.Errorf("dispatcher is closed")
This error is repeated. I think we should declare as follows. This allows the caller to use the error in some future case.
```golang
var ErrDispatcherClosed = fmt.Errorf("dispatcher is closed")
```

2022-05-23 13:16 UTC, Harkishen-Singh commented on pkg/pgmodel/ingestor/ingestor_test.go
> +	"go.uber.org/atomic"
Can we place this above promscale imports?

2022-05-23 13:29 UTC, Harkishen-Singh approved these changes

2022-05-24 07:55 UTC, Harkishen-Singh commented on pkg/pgmodel/ingestor/dispatcher.go
> +		return 0, fmt.Errorf("dispatcher is closed")
```suggestion
		return 0, ErrDispatcherClosed
```

2022-05-24 08:36 UTC, antekresic approved these changes
lgtm

2022-05-24 09:05 UTC, merged