Adds support for reloader in Promscale.
timescale/promscale pull request #1426
Opened 2022-06-10 13:09 UTC by Harkishen-Singh

Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

## Description

*Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.*

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

2022-06-14 08:12 UTC, niksajakovljevic requested changes
Imho this is over-engineered. The code could be simplified a lot. We only need to reload rules.

2022-06-14 12:18 UTC, niksajakovljevic reviewed
Looks good. I'd just like to see some tests (either unit or e2e)

2022-06-15 07:37 UTC, antekresic commented on pkg/runner/runner.go
> +		reloadRules = rulesReloader
I'd rather you declare the manager var before NewManager than doing this, so you can use `=` vs `:=`.

2022-06-15 07:37 UTC, antekresic commented on pkg/tests/end_to_end_tests/rules_test.go
> +			require.NoError(t, manager.Run(), "error running rules manager")
This won't wait for the manager.Run to return a result.

2022-06-15 07:37 UTC, antekresic commented on pkg/tests/end_to_end_tests/rules_test.go
> +		// Check for rules.
Try reloading rules before changing them to see if anything changes.

2022-06-15 07:37 UTC, antekresic commented on pkg/tests/end_to_end_tests/rules_test.go
> +		rulesCfg.PrometheusConfigAddress = EmptyRecordingRulesConfigPath
What if we used empty rules first and then reload to actual rules and wait?

2022-06-16 07:29 UTC, antekresic approved these changes

2022-06-16 07:29 UTC, merged