Adds support for network latency metric.
timescale/promscale pull request #1431
Opened 2022-06-14 11:41 UTC by Harkishen-Singh

Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

Fixes: https://github.com/timescale/o11y-team-applications/issues/194

## Description

*Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.*

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

2022-06-15 10:08 UTC, niksajakovljevic commented
@Harkishen-Singh Can you please explain in the description what do you mean by network latency.

2022-06-15 10:08 UTC, paulfantom commented on docs/mixin/dashboards/promscale.json
> +      "label": "Promscale metrics",
Can we not change this?

2022-06-15 10:09 UTC, paulfantom commented on docs/mixin/dashboards/promscale.json
> +      },
I am not sure if static UID should be present here :thinking:

2022-06-15 11:11 UTC, niksajakovljevic reviewed
Let's discuss how to consolidate the code since we've introduced a snowflake.

2022-06-15 11:11 UTC, niksajakovljevic commented on pkg/pgmodel/metrics/database/metrics.go
> -	{
We should make it clear why we us another approach over existing one, or if needed we consider extending existing solution to support this use-case.

2022-06-16 10:45 UTC, Harkishen-Singh commented on pkg/pgmodel/metrics/database/metrics.go
> -	{
Now we use the existing approach, which also protects the /metrics from getting hammered.

2022-06-16 10:45 UTC, Harkishen-Singh commented on pkg/pgmodel/metrics/database/metrics.go
> -	{
Now we use the existing approach, which also protects the /metrics from getting hammered.

2022-06-16 10:46 UTC, Harkishen-Singh commented on pkg/pgmodel/metrics/database/metrics.go
> +			err := conn.QueryRow(context.Background(), "SELECT 1").Scan(&val)
Can you please suggest how to do a batch level SQL timeout? We do have context timeout, but there was a discussion to add a txn level statement_timeout. I tried looking into previously, but couldn't understand how to add a batch level statement_timeout.

2022-06-16 10:46 UTC, Harkishen-Singh commented on pkg/pgmodel/metrics/database/metrics.go
> +			err := conn.QueryRow(context.Background(), "SELECT 1").Scan(&val)
Can you please suggest how to do a batch level SQL timeout? We do have context timeout, but there was a discussion to add a txn level statement_timeout. I tried looking into previously, but couldn't understand how to add a batch level statement_timeout.

2022-06-17 09:09 UTC, paulfantom reviewed
I looked only at dashboard and it looks good to me apart from one minor issue mentioned in an inline comment.

2022-06-17 09:09 UTC, paulfantom commented on docs/mixin/dashboards/promscale.json
> +      "collapsed": false,
Could you manually change this to `true` as it was before?

2022-06-20 13:28 UTC, antekresic requested changes

2022-06-20 13:28 UTC, antekresic commented on pkg/pgmodel/metrics/database/database.go
> +		dbNetworkLatency.Set(float64(networkLatency))
Wrap this into a function and call on line 120

2022-06-21 09:15 UTC, antekresic approved these changes

2022-06-21 09:19 UTC, niksajakovljevic approved these changes

2022-06-21 09:34 UTC, paulfantom commented
Mixin CI check is failing due to https://github.com/timescale/promscale/issues/1446. You can safely ignore it for now.

2022-06-21 10:24 UTC, merged