Prepare for the 0.12.0 release
timescale/promscale pull request #1438
Opened 2022-06-17 12:33 UTC by niksajakovljevic

2022-06-17 12:34 UTC, Harkishen-Singh approved these changes

2022-06-17 13:14 UTC, paulfantom commented on .goreleaser.yml
> -  name_template: "{{ .Binary }}_0.0.3_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
Could you create an issue to move this hardcoded value out of `.goreleaser.yml`? We shouldn't change this file on each prom-migrator release.

2022-06-17 13:16 UTC, paulfantom approved these changes
LGTM on green.

2022-06-21 07:35 UTC, JamesGuthrie requested changes

2022-06-21 07:35 UTC, JamesGuthrie commented on CHANGELOG.md
> +## [0.12.0] - 2022-06-17
```suggestion
## [0.12.0] - 2022-06-21
```

2022-06-21 07:39 UTC, JamesGuthrie approved these changes

2022-06-21 07:59 UTC, merged