Ingest metric data with COPY to get better performance
timescale/promscale pull request #1462
Opened 2022-06-29 15:07 UTC by niksajakovljevic

2022-07-06 09:54 UTC, niksajakovljevic commented
Due to recent changes in the extension I needed to temporarily tweak `EXTENSION` to be able to run e2e tests. I believe long term we want to trigger e2e tests on the new branch from the extension side.

2022-07-08 09:37 UTC, Harkishen-Singh requested changes
The implementation looks good. We should have some end-to-end test, that can stimulate normal COPY ingest and with conflict.

2022-07-08 09:37 UTC, Harkishen-Singh commented on pkg/pgmodel/ingestor/copier.go
> +		return fmt.Errorf("failed to start TX for inserting metrics: %v", err), lowestMinTime
```suggestion
		return fmt.Errorf("failed to start transaction for inserting metrics: %w", err), lowestMinTime
```

2022-07-08 09:48 UTC, niksajakovljevic commented
@Harkishen-Singh There are existing e2e tests for testing various duplicate scenarios (check `create_test.go`).

2022-07-08 11:09 UTC, Harkishen-Singh approved these changes

2022-07-08 11:10 UTC, niksajakovljevic commented on pkg/pgmodel/ingestor/copier.go
> +			table := pgx.Identifier{schema.PromDataExemplar, req.info.TableName}
Yep, will try to improve that part a bit

2022-07-08 11:54 UTC, niksajakovljevic commented on pkg/pgmodel/ingestor/copier.go
> +				table, err = createTempIngestTable(ctx, tx, req.info.TableName, req.info.TableSchema, fmt.Sprintf("s%d_", r))
I don't think that's true. Temporary tables are bound to a session/connection. That is by design.

2022-07-08 12:01 UTC, niksajakovljevic commented on pkg/pgmodel/ingestor/copier.go
> +				table, err = createTempIngestTable(ctx, tx, req.info.TableName, req.info.TableSchema, fmt.Sprintf("s%d_", r))
Related discussion https://github.com/timescale/promscale_extension/pull/401#discussion_r916747127

2022-07-08 13:31 UTC, antekresic approved these changes
Minor nit, looks good otherwise :tada:

2022-07-08 13:31 UTC, antekresic commented on pkg/pgmodel/ingestor/copier.go
> +				res, err := tx.Exec(ctx, fmt.Sprintf(sqlInsertIntoFrom, schema.PromDataExemplar, pgx.Identifier{req.info.TableName}.Sanitize(),
Minor nit: if the argument list is multiline, lets put all of them on new lines. Easier to read.

2022-07-08 15:05 UTC, merged