Fix double counting while populating `promscale_sql_database_chunks_count` metric
timescale/promscale pull request #1494
Opened 2022-07-15 06:22 UTC by arajkumar

## Description

### Problem statment
`PromscaleCompressionLow` alert fires regardless of a good compression ratio.

### Root cause

SQL query which populates `promscale_sql_database_chunks_count` is a sum of the below metrics,
1) Uncompressed Chunks
2) Proxy Chunks which points to Compressed Chunks
3) Compressed Chunks

However the total chunk count should be just (1) + (3), because (2) is already pointing to (3) and which leads to double counting.

### Solution

Fix the SQL query to consider entries which has `compressed_chunk_id` as null and this will be true for both (1) and (3).

Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

2022-07-15 08:17 UTC, alejandrodnm approved these changes

2022-07-15 08:17 UTC, alejandrodnm commented on pkg/tests/end_to_end_tests/database_metrics_test.go
> +		require.Equal(t, chunksCount, float64(3))
nit:
```suggestion
		require.Equal(t, float64(3), chunksCount)
```

2022-07-15 10:35 UTC, arajkumar commented on pkg/tests/end_to_end_tests/database_metrics_test.go
> +		require.Equal(t, chunksCount, float64(3))
What a blooper :P

2022-07-15 11:03 UTC, JamesGuthrie requested changes
minor nit

2022-07-15 11:03 UTC, JamesGuthrie commented on docs/runbooks/PromscaleCompressionLow.md
> +6. Check number of maintenancec jobs: `select count(*) from timescaledb_information.jobs where proc_name = 'execute_maintenance_job'`
```suggestion
6. Check number of maintenance jobs: `select count(*) from timescaledb_information.jobs where proc_name = 'execute_maintenance_job'`
```

2022-07-15 12:43 UTC, JamesGuthrie approved these changes

2022-07-18 07:08 UTC, antekresic approved these changes

2022-07-18 08:30 UTC, alejandrodnm commented on pkg/tests/end_to_end_tests/database_metrics_test.go
> +		require.Equal(t, chunksCount, float64(3))
It has happened to me soooo many times.

2022-07-18 09:41 UTC, merged