Add cmd flag to skip http paths from authentication
timescale/promscale pull request #1637
Opened 2022-09-12 08:28 UTC by arajkumar

Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>

## Description

This PR adds a flag named `--web.auth.ignore-path` which takes a http path and passed path would be ignored from authentication. The flag shall be repeated to pass array of ignored paths.

e.g.
```
# skips authn for heathz and api/query_range endpoints.
./dist/promscale --web.auth.ignore-path=/heathz --web.auth.ignore-path=/api/query_range
```

Fixes https://github.com/timescale/promscale/issues/1636

## Merge requirements

Please take into account the following non-code changes that you may need to make with your PR:

- [ ] CHANGELOG entry for user-facing changes
- [ ] Updated the relevant documentation

2022-09-13 08:18 UTC, alejandrodnm commented on pkg/api/router.go
> +	isIgnoredPath := func(r *http.Request) bool {
Maybe we can add this as a method to `Auth`?

2022-09-13 08:18 UTC, alejandrodnm approved these changes

2022-09-13 09:02 UTC, antekresic requested changes
Overall looks good, a bit of organization would benefit us here with the rise of complexity in the auth code.

2022-09-14 08:51 UTC, Harkishen-Singh commented
I will pass this review to other reviewers.

2022-09-14 15:41 UTC, alejandrodnm approved these changes

2022-09-15 07:49 UTC, antekresic approved these changes
Approved with a small ask to add a TODO for some future refactoring.

2022-09-15 07:49 UTC, antekresic commented on pkg/api/router.go
> +func GenerateRouter(apiConf *Config, promqlConf *query.Config, client *pgclient.Client, store *jaegerStore.Store, authWrapper mux.MiddlewareFunc, reload func() error) (*mux.Router, error) {
This is obviously a smell, having so many input parameters on a function. The function itself is too big as well.

Lets put a TODO on this to refactor it in the future so when somebody goes to add another parameter, they can see it and not do it 😃

2022-09-15 08:45 UTC, merged