Adds support for checking pg server version number on startup
timescale/promscale pull request #273
Opened 2020-09-28 07:23 UTC by Harkishen-Singh

Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

Current valid range: `>=110000 <129999`.

2020-10-07 20:29 UTC, cevian requested changes

2020-10-07 20:29 UTC, cevian commented on pkg/pgmodel/extension.go
> +	if err := conn.QueryRow(context.Background(), "SHOW server_version_num;").Scan(&versionString); err != nil {
This should be "SHOW server_version;"  which will return a X.Y number like "12.2" -> convert to semver via "%s.0"
https://www.postgresql.org/support/versioning/

2020-10-07 20:29 UTC, cevian commented on pkg/version/version.go
> +	PgVersionNumRange       = ">=110000.0.0 <129999.0.0" // Corresponds to range within pg 11.00.00 to pg 12.99.99
we don't support 11  so this should be "=12.x" after the change I propose above

2020-10-08 14:50 UTC, Harkishen-Singh commented
@cevian done!

2020-10-09 12:52 UTC, cevian requested changes

2020-10-09 12:52 UTC, cevian commented on pkg/version/version.go
> +	PgVersionNumRange       = "=12.x" // Corresponds to range within pg 11.00.00 to pg 12.99.99
```suggestion
	PgVersionNumRange       = "=12.x" // Corresponds to range within pg 12.0 to pg 12.99
```

2020-10-09 12:52 UTC, cevian commented on pkg/pgmodel/extension.go
> +			fmt.Sprintf("%s to %s", strings.Split(version.PgVersionNumRange, " ")[0], strings.Split(version.PgVersionNumRange, " ")[1]),
There is no range here so nothing to split. Let's just do:
```
log.Error(
			"msg", "incompatible postgresql version", "supported server version range", version.PgVersionNumRange)
```

2020-10-10 21:37 UTC, cevian requested changes

2020-10-10 21:37 UTC, cevian commented on pkg/pgmodel/extension.go
> +		log.Error("msg", "incompatible postgresql version", "supported server version range", version.PgVersionNumRange)
This should be returned as an error (fmt.Errorf) not simply logged.

2020-10-10 21:37 UTC, cevian commented on pkg/pgmodel/extension.go
> +		return fmt.Errorf("pg-version: %w", err)
```suggestion
		return fmt.Errorf("Problem checking PostgreSQL version: %w", err)
```

2020-10-10 21:37 UTC, cevian commented on pkg/pgmodel/extension.go
> +		return fmt.Errorf("extensions-version: %w", err)
```suggestion
		return fmt.Errorf("Problem checking Promescale extension version: %w", err)
```

2020-10-12 16:29 UTC, cevian approved these changes

2020-10-15 14:27 UTC, cevian approved these changes
Couple of nits left

2020-10-15 14:27 UTC, cevian commented on pkg/pgmodel/extension.go
> +	var tmp string
I think this should use `strings.TrimLeft(s,"0")`

2020-10-15 14:27 UTC, cevian commented on pkg/pgmodel/extension.go
> +	versionString = fmt.Sprintf("%s.%s.0", versionString[:2], formatPgVersion(versionString[4:]))
Please add a comment about what this conversion is doing

2020-10-22 19:41 UTC, merged