fix `trimLeadingZeros()`
timescale/promscale pull request #392
Opened 2020-12-19 22:28 UTC by hacker

if there's nothing but zeroes in the version component it happens to strip
one too many for it should tolerate one leading zero if it also happens
to be a trailing one.

2020-12-19 22:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/timescale/promscale?pullRequest=392) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/timescale/promscale?pullRequest=392) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/timescale/promscale?pullRequest=392) it.</sub>

2020-12-21 06:13 UTC, Harkishen-Singh requested changes
Thank you for this PR :1st_place_medal: 

Also, please sign the contributors license. It should not take more than a minute.

2020-12-21 06:13 UTC, Harkishen-Singh commented on pkg/pgmodel/extension.go
> +	return rv
```suggestion
	if s = strings.TrimLeft(s, "0"); s == "" {
		return "0"
	}
	return s
```

Let's re-use the same variable.

2020-12-21 13:38 UTC, hacker commented
Sure. Was hoping you don't really care, especially for four-liner ;-) I hate paperwork.

2020-12-23 14:38 UTC, antekresic commented
Sorry to bother you again. Would you mind squashing the commits and rebasing them on the current master?

I will merge this in immediately after that, I promise! :slightly_smiling_face:

2020-12-23 19:39 UTC, hacker commented
Like this?

2020-12-24 06:58 UTC, Harkishen-Singh approved these changes
Lgtm! Thank you very much for your contribution. 😀

2020-12-24 07:02 UTC, merged

2020-12-24 07:03 UTC, antekresic commented
Thanks for your contribution! :slightly_smiling_face:

2020-12-24 08:02 UTC, hacker commented
You're welcome :)