Improve logs when connector unable to migrate.
timescale/promscale pull request #455
Opened 2021-01-27 17:31 UTC by Harkishen-Singh

Signed-off-by: Harkishen-Singh <harkishensingh@hotmail.com>

Fixes: #444

2021-01-28 14:12 UTC, blagojts approved these changes

2021-01-29 00:34 UTC, cevian requested changes

2021-01-29 00:34 UTC, cevian commented on pkg/util/lock.go
> +		return fmt.Errorf("unable to get schema lock. Please make sure that no Promscale connectors are running: %w", err)
```suggestion
		return fmt.Errorf("Unable to get shared schema lock. Please make sure that no operations requiring exclusive locking : %w", err)
```

2021-01-29 00:34 UTC, cevian commented on pkg/pgmodel/migrate.go
> +		return fmt.Errorf("error while comparing schema version. This can cause issues while schema migration. Received schema version %v but expected %v. Please note that no Promscale connectors are runni
We should only print this message if we couldn't get the schema lock. That means we need to pass the variable that says whether or not the exclusive schema lock was obtained down to here

2021-01-29 16:59 UTC, cevian requested changes

2021-01-29 16:59 UTC, cevian commented on pkg/pgmodel/migrate.go
> +func CheckSchemaVersion(ctx context.Context, conn *pgx.Conn, versionInfo VersionInfo, hasSharedLease bool) error {
I think there is confusion here what we care about is not the shared lease lock but the exclusive migration lock

2021-01-29 16:59 UTC, cevian commented on pkg/pgmodel/migrate.go
> +	if err = CheckSchemaVersion(context.Background(), db, versionInfo, true); err != nil { // We pass hasSharedLease as true since it has already been verified at the start.
What we should be passing down is `migrationFailedDueToLockError` not anything about the shared lease

2021-01-29 16:59 UTC, cevian commented on pkg/pgmodel/migrate.go
> +			return fmt.Errorf("Error while comparing schema version. Failed to acquire shared schema lock. Please ensure that no Promscale connectors are running that can prevent from schema migration due to
```suggestion
			return fmt.Errorf("Failed to acquire the migration lock to upgrade the schema version and unable to run with the old version. Please ensure that no other Promscale connectors with the old schema version are running. Received schema version %v but expected %v", dbVersion, expectedVersion)
```

2021-01-29 16:59 UTC, cevian commented on pkg/pgmodel/migrate.go
> +		if !hasSharedLease {
```suggestion
		if  dbVersion.Compare(expectedVersion)  < 0 && !hasSharedLease {
```

2021-01-29 16:59 UTC, cevian commented on pkg/runner/runner.go
> +	return pgmodel.CheckSchemaVersion(ctx, conn, appVersion, hasSharedLease)
yeah this is not the path we are worried about. The shared lease doesn't matter much

2021-01-31 16:15 UTC, cevian approved these changes
Minor changes asked, but good to merge otherwise. Thanks!

2021-01-31 16:15 UTC, cevian commented on pkg/util/lock.go
> +		return fmt.Errorf("Unable to get shared schema lock. Please make sure that no operations requiring exclusive locking: %w", err)
```suggestion
		return fmt.Errorf("Unable to get shared schema lock. Please make sure that no operations requiring exclusive locking are running: %w", err)
```

2021-01-31 16:15 UTC, cevian commented on pkg/pgmodel/migrate.go
> +	if versionState := dbVersion.Compare(expectedVersion); versionState != 0 {
```suggestion
	if versionCompare := dbVersion.Compare(expectedVersion); versionCompare != 0 {
```

2021-02-01 03:46 UTC, merged