Add new docker-compose file to use without build dependency
timescale/promscale pull request #533
Opened 2021-03-16 19:34 UTC by VineethReddy02

Add a docker-compose file without dependency to build Promscale image on setting up Promscale. i.e. removed from Promscale service.

```
    build:
      context: .
```

2021-03-17 00:59 UTC, cevian commented
@VineethReddy02 I don't understand your point about the error?

2021-03-17 06:45 UTC, VineethReddy02 commented
In the current docker-compose file. We mention building a Promscale image by providing `build:context: .` this needs Dockerfile to do so. If a user wants to run Promscale this is adding a dependency to clone promscale Github repo or to manually add Promscale Dockerfile. 

Adding the new docker-compose file in this PR removes such dependency. Now users can just use docker-compose file from this PR as the Promscale image build step has been removed.

2021-04-13 19:38 UTC, cevian requested changes
I think this new file should be called docker-compose/docker-compose.yaml and the old one be renamed docker-compose/docker-compose-with-build.yaml and we should put comments in both files to update them in sync

2021-05-04 11:47 UTC, VineethReddy02 commented
@cevian I am removing the `build: context: .` from `docker-compose.yaml` as in `test.sh` we are already explicitly building the Promscale image with cmd `docker build -t timescale/promscale:latest ../.. --file ../../build/Dockerfile` and tagging it to `promscale:latest`.

2021-05-05 01:02 UTC, cevian approved these changes

2021-05-05 05:51 UTC, VineethReddy02 commented
bors r+

2021-05-05 06:01 UTC, merged