Docs for multi-tenancy.
timescale/promscale pull request #620
Opened 2021-05-06 11:36 UTC by Harkishen-Singh

Signed-off-by: Harkishen Singh <harkishensingh@hotmail.com>

2021-05-10 06:38 UTC, antekresic approved these changes
Couple of nits, looks good in general.

2021-05-10 06:38 UTC, antekresic commented on README.md
> +* **[High Availability](docs/high-avaliability/prometheus-HA.md)**
```suggestion
* **[High Availability](docs/high-availability/prometheus-HA.md)**
```

2021-05-10 06:38 UTC, antekresic commented on docs/multi_tenancy.md
> +3. `metric_name` then data from `metric_name` will be from the non-tenants, `tenant-A` and `tenant-B` respectively.
Add another example to query non-tenant data only?

2021-05-17 01:03 UTC, cevian requested changes

2021-05-17 01:03 UTC, cevian commented on docs/multi_tenancy.md
> +Imagine if Promscale contains data from `tenant-A`, `tenant-B` and `tenant-C`. If Promscale is applied with
```suggestion
Imagine if Promscale contains data from `tenant-A`, `tenant-B` and `tenant-C`. If Promscale is configured with
```

2021-05-17 01:03 UTC, cevian commented on docs/multi_tenancy.md
> +    not from `tenant-C`. This is because `tenant-C` is not a valid tenant for the current session of Promscale.
```suggestion
    not from `tenant-C`. This is because the Promscale instance is configured to return data from only `tenant-A` and `tenant-B`.
```

2021-05-17 01:03 UTC, cevian commented on docs/multi_tenancy.md
> +Now, if the same database also contains data from non-tenants and `-multi-tenancy-allow-non-tenants` is applied then
```suggestion
Now, if the same database also contains samples without any tenant label and `-multi-tenancy-allow-non-tenants` is applied then
```

2021-06-08 22:06 UTC, cevian approved these changes

2021-06-08 22:06 UTC, cevian commented on docs/multi_tenancy.md
> +you will require applying flags on other Promscale instances as well (If you want them to participate in multi-tenant operations).
```suggestion
Remember to set the appropriate CLI flags on all of your promscale instances.
```

2021-06-09 11:04 UTC, Harkishen-Singh commented
bors r+

2021-06-09 11:14 UTC, merged