Update Prompb with upstream upto May 7.
timescale/promscale pull request #657
Opened 2021-06-07 09:16 UTC by Harkishen-Singh

Signed-off-by: Harkishen Singh <harkishensingh@hotmail.com>

This commit updates the Prompb with Upstream including all changes
till May 7. This includes changes done till commit
8fd73b1d281d3227c337b291e8c797a85251d3d5.

The major feature of this commit is the support of Exemplars.

2021-06-07 16:38 UTC, cevian requested changes
We need to implement our changes for exemplars that would make good reuse of our object pool

2021-06-07 16:38 UTC, cevian commented on pkg/prompb/types.pb.go
> +			m.Exemplars = append(m.Exemplars, Exemplar{})
We should implement the same optimizations we do for samples (maybe separate commit same pr)
```suggestion
			if len(m.Examplars) < cap(m.Examplars) {
				m.Examplars = m.Examplars[:len(m.Examplars)+1]
				m.Examplars[len(m.Examplars)-1].Reset()
			} else {
				m.Examplars = append(m.Examplars, Examplars{})
			}
```
in custom.ts.go we need
```
func (m *TimeSeries) Reset() {
	*m = TimeSeries{Labels: m.Labels[:0], Samples: m.Samples[:0], Examplars: m.Exemplars[:0]}
}
```

2021-06-07 16:38 UTC, cevian commented on pkg/prompb/types.pb.go
> +			m.Labels = append(m.Labels, Label{})
We also need to implement the same slice-reuse logic here

2021-06-07 16:38 UTC, cevian commented on pkg/prompb/types.pb.go
> +func (m *Exemplar) Reset()         { *m = Exemplar{} }
this should be moved to custom.ts.go and we should implement the slice-reuse logic

2021-06-08 19:10 UTC, Harkishen-Singh commented
Bors r+

2021-06-08 19:21 UTC, merged