Fixes Promscale on TimescaleDB-OSS.
timescale/promscale pull request #659
Opened 2021-06-08 09:22 UTC by Harkishen-Singh

Signed-off-by: Harkishen Singh <harkishensingh@hotmail.com>

Fixes: #583 

**Note:** I tried to apply conditional checks where I felt would be necessary. There are high chances that I have missed them out at important places, please keep this in mind while reviewing.

TODO:

- [x] E2E for TimescaleDB-OSS version

2021-06-10 10:01 UTC, antekresic requested changes
Missing check in `config_maintenance_jobs`, uses user-defined actions which are not in OSS:
https://docs.timescale.com/api/latest/actions/

2021-07-07 00:56 UTC, cevian requested changes

2021-07-16 14:44 UTC, cevian approved these changes
Looks good. I do however want to add a big WARNING when promscale first starts up if we are using OSS to warn people: 
```
WARNING: Using the Apache2 version of TimescaleDB. This version does not include compression and thus performance and disk usage will be significantly negatively effected.
```

2021-07-16 15:55 UTC, Harkishen-Singh commented
bors r+

2021-07-19 07:27 UTC, antekresic approved these changes
Some minor nits, should be good to go.

2021-07-19 07:27 UTC, antekresic commented on pkg/migrations/sql/idempotent/base.sql
> +    $func$
Minor nit: why add whitespace here? It even makes things harder to read.

2021-07-19 07:27 UTC, antekresic commented on pkg/runner/client.go
> +		return false, fmt.Errorf("fetching if TimescaleDB is installed: %w", err)
```suggestion
		return false, fmt.Errorf("error fetching if TimescaleDB is installed: %w", err)
```

2021-07-19 07:27 UTC, antekresic commented on pkg/runner/client.go
> +		return false, fmt.Errorf("fetching TimescaleDB license: %w", err)
```suggestion
		return false, fmt.Errorf("error fetching TimescaleDB license: %w", err)
```

2021-07-19 07:39 UTC, Harkishen-Singh commented
bors r+

2021-07-19 07:49 UTC, merged