Add support of Thanos Store grpc-service protocol to make able connect Promscale to Thanos Query
timescale/promscale pull request #664
Opened 2021-06-15 06:36 UTC by 2nick

> 1. How is this helpful?

This PR adds functionality that allows using Promscale as part of [Thanos](https://github.com/thanos-io/thanos/) infrastructure.

Thanos is usually used with massive Prometheus installations and allows to run queries with metrics located on different Prometheus instances.

Connecting Promscale to Thanos Query component allows making queries that use metrics stored in TimescaleDB.

> 2. Aims behind the implementation. Are you trying to achieve something?

At first, I'd tried to use remote-read in Promscale with Thanos Sidecar which allows adding Prometheus instance to Thanos infrastructure.

But there is a problem that Thanos Sidecar trying to read Prometheus config through [/api/v1/status/config](https://prometheus.io/docs/prometheus/latest/querying/api/#config) to get external labels and Promscale has no such endpoint. Also sidecar won't start without external labels.

The main problem is that when Prometheus has external labels it will add them to samples when sends the stream to remote write and Thanos Sidecar add them when sends request to remote read. 

And if you had added some metrics without those external labels directly to TimescaleDB you wouldn't select them because Thanos Sidecar will add external labels to chunks select request.

For me it looks like adding the functionality of Thanos Store to Promscale is the best option here. :)

2021-06-21 15:20 UTC, 2nick commented
@Harkishen-Singh could you please take look at this description and PR? :)

2021-06-21 15:43 UTC, cevian commented
@2nick Thaks for this PR. I am going to get in touch with some Thanos developers to see if we can get some thoughts on this PR as well. I'll update shortly.

Thank you, Mat

2021-07-01 18:12 UTC, cevian requested changes
This looks great. Only small changes requested. Will approve and merge once the changes are implemented. Thanks @2nick.

2021-07-01 18:12 UTC, cevian commented on pkg/runner/runner.go
> +		log.Info("msg", fmt.Sprintf("Start listening %s", cfg.GrpcListenAddr))
```suggestion
		log.Info("msg", fmt.Sprintf("Start listening for Thanos StoreAPI on %s", cfg.GrpcListenAddr))
```

2021-07-01 18:12 UTC, cevian commented on pkg/runner/runner.go
> +			log.Error("msg", "Listening grpc-server", "err", err)
```suggestion
			log.Error("msg", "Listening for Thanos StoreAPI failed", "err", err)
```

2021-07-01 18:12 UTC, cevian commented on pkg/runner/runner.go
> +			log.Error("msg", "Starting grpc-server", "err", err)
```suggestion
			log.Error("msg", "Starting the Thanos store failed", "err", err)
```

2021-07-01 18:12 UTC, cevian commented on go.mod
> -	github.com/shurcooL/vfsgen v0.0.0-20200824052919-0d455de96546 // indirect
why are these indirect dependencies removed

2021-07-02 23:50 UTC, 2nick commented on go.mod
> -	github.com/shurcooL/vfsgen v0.0.0-20200824052919-0d455de96546 // indirect
Don't know, probably by go mod tidy

2021-07-03 11:29 UTC, 2nick commented on pkg/runner/flags.go
> +	fs.StringVar(&cfg.GrpcListenAddr, "grpc-listen-address", ":9202", "Address to listen on for Thanos Store endpoints.")
Should I change config field name too?

2021-07-03 16:07 UTC, cevian commented on pkg/runner/flags.go
> +	fs.StringVar(&cfg.GrpcListenAddr, "grpc-listen-address", ":9202", "Address to listen on for Thanos Store endpoints.")
that would be great if you could

2021-07-10 09:12 UTC, 2nick commented
Actualized to 0.5.0

2021-07-13 20:37 UTC, cevian approved these changes

2021-07-13 20:42 UTC, cevian commented
@andersje there is a conflict in go.sum if you resolve that then do a "bors r+" in comments to merge. **Thanks again**

2021-07-27 09:49 UTC, antekresic commented
bors r+

2021-07-27 10:35 UTC, antekresic commented
bors r+

2021-07-27 10:44 UTC, merged

2021-08-10 12:47 UTC, ramonguiu commented
@2nick thanks so much for helping improve Promscale to be integrated in a Thanos installation.
Would you be interested in contributing a post on the Timescale blog (with our help) on the problem you wanted to solve, the process to get everything set up and the value you get from it?