Pushdown rate and increase optimizations
timescale/promscale pull request #673
Opened 2021-06-25 20:30 UTC by cevian

These function were actually supported in the extension before
but weren't being pushed down. This commit fixes that. 

Depends and is rebased on #666

2021-06-29 07:20 UTC, antekresic requested changes

2021-06-29 07:20 UTC, antekresic commented on pkg/pgmodel/querier/query_builder.go
>  func getAggregators(hints *storage.SelectHints, qh *QueryHints, path []parser.Node) (*aggregators, parser.Node, error) {
This function needs a bit of refactoring. 

I suggest handling the various checks that overlap for all pushdowns first and returning the no optimization path as soon as possible based on them. Things like is the extension installed or if there is a subquery should be checked as soon as possible.

Should make the rest of the code much more easier to read and maintain.

2021-06-29 07:20 UTC, antekresic commented on pkg/pgmodel/querier/query_builder.go
> +			panic("query start should equal query end")
Should we be panicking here? This will kill Promscale just because hints details were unexpected.

2021-06-29 08:33 UTC, Harkishen-Singh approved these changes
Looks good except, I agree on Ante's comments.

2021-06-30 07:08 UTC, antekresic approved these changes
I have a minor suggestion that isn't crucial. Otherwise, this looks good to me :+1:

2021-06-30 07:08 UTC, antekresic commented on pkg/pgmodel/querier/query_builder.go
> +			switch n := node.(type) {
Minor nit: seems the code would be a bit cleaner if we used switch case on `n.Func.Name` and an if clause for the `node.(type)`. Hopefully, in the future, we will add support for more pushdown functions so this change makes even more sense.

2021-06-30 12:33 UTC, cevian commented
bors r+

2021-06-30 13:02 UTC, merged