Mem optimizations on query path
timescale/promscale pull request #675
Opened 2021-06-29 18:21 UTC by cevian

Look at commit comments

2021-06-30 08:24 UTC, antekresic approved these changes
Looks good!

2021-06-30 08:24 UTC, antekresic commented on pkg/pgmodel/querier/querier.go
> +//SerieSet adds a Close method to storage.SeriesSet to provide a way to free memory
```suggestion
// SeriesSet adds a Close method to storage.SeriesSet to provide a way to free memory
```

2021-07-01 07:30 UTC, Harkishen-Singh requested changes
Few comments.

2021-07-01 07:30 UTC, Harkishen-Singh commented on pkg/pgmodel/querier/row.go
> +func (dstwrapper *float8ArrayWrapper) DecodeBinary(ci *pgtype.ConnInfo, src []byte) error {
If the purpose of these funcs is to just reuse the `pgtype.Float8Array` allocations, why not just do this way:

```golang
func PutFloat8Array(ref *pgtype.Float8Array) {
    ref.ArrayDimensions = pgtype.ArrayDimensions{}
    ref.Set(nil)
    fPool.Put(ref)
}
```

Same applies for TimestamptzArray.

ref: https://github.com/jackc/pgtype/blob/2ca304d4617a72491b1844eb92e9ecd86f7b84e9/float8_array.go#L22

2021-07-01 07:30 UTC, Harkishen-Singh commented on pkg/pgmodel/querier/timestamp_series.go
> +func NewRowTimestampSeries(times *pgtype.TimestamptzArray) *rowTimestampSeries {
Do we need this exported? If I am not wrong, its being used in the querier package only. Same applies to `NewRegularTimestampSeries()` too.

2021-07-01 14:14 UTC, Harkishen-Singh approved these changes

2021-07-01 15:05 UTC, cevian commented
bors r+

2021-07-01 15:38 UTC, merged