Add data retention support for metric views based on continuous aggregates
timescale/promscale pull request #712
Opened 2021-08-03 10:48 UTC by antekresic

Continuous aggregates rely on hypertables to store their aggregated data. This
change tries to check for metric views which are based on them to apply the same
data retention system as for raw metric data. Users will be able to set data
retention rules for them same as for other raw metrics.

2021-08-03 15:30 UTC, cevian requested changes
Looks good. But, I have asked for some more tests.

2021-08-03 15:30 UTC, cevian commented on pkg/migrations/sql/idempotent/base.sql
> +CREATE OR REPLACE FUNCTION SCHEMA_CATALOG.get_metric_hypertable_info(metric_schema_name text, metric_table_name text, is_view boolean)
nit: makes it more clear it's where the data is stored not the raw hypertable
```suggestion
CREATE OR REPLACE FUNCTION SCHEMA_CATALOG.get_storage_hypertable_info(metric_schema_name text, metric_table_name text, is_view boolean)
```

2021-08-03 15:30 UTC, cevian commented on pkg/tests/end_to_end_tests/continuous_agg_test.go
> +		//time.Sleep(18000 * time.Second)
```suggestion
	
```

2021-08-03 15:30 UTC, cevian commented on pkg/tests/end_to_end_tests/continuous_agg_test.go
>  	"github.com/timescale/promscale/pkg/internal/testhelpers"
I think we need some tests to make sure that  the top-level `execute_data_retention_policy` does the right thing with views and that `set_metric_retention_period` works on caggs as well.

2021-08-03 16:39 UTC, antekresic commented on pkg/tests/end_to_end_tests/continuous_agg_test.go
> +		err = db.QueryRow(context.Background(), `SELECT count(*) FROM cagg_schema.cagg`).Scan(&count)
Umm, this is a test? 😀

2021-08-03 16:58 UTC, jgpruitt commented on pkg/tests/end_to_end_tests/continuous_agg_test.go
> +		err = db.QueryRow(context.Background(), `SELECT count(*) FROM cagg_schema.cagg`).Scan(&count)
Ahh... yes. Never mind 🤣

2021-08-04 17:10 UTC, jgpruitt commented on pkg/migrations/sql/idempotent/base.sql
>  ) RETURNS BIGINT[]
Are we worried that `DROP FUNCTION ... CASCADE` could possibly drop users' code if they have built functions, procedures, or views on top of these functions?

2021-08-04 22:55 UTC, cevian reviewed
Everything looks good with tests now. the only remaining question is the changes to the metric admin function UIUX

2021-08-04 22:55 UTC, cevian commented on pkg/migrations/sql/idempotent/base.sql
> +CREATE OR REPLACE FUNCTION SCHEMA_CATALOG.get_metric_retention_period(schema_name TEXT, metric_name TEXT)
This isn't a great interface change TBH from the UIUX point of view. Maybe this should be the second parameter but with a default value of 'prom_data'. I know that violates the argument ordering though. I think this needs a larger discussion.

2021-08-04 22:55 UTC, cevian commented on pkg/migrations/sql/idempotent/base.sql
> +-- Get metric hypertable information for raw and cagg metrics
```suggestion
-- Get hypertable information for where data is stored for raw metrics and for 
-- the materialized hypertable for cagg metrics. For non-materialized views return 
-- no rows
```

2021-08-09 05:14 UTC, antekresic commented on pkg/migrations/sql/idempotent/base.sql
>  ) RETURNS BIGINT[]
Removed CASCADE from all DROPs.

2021-08-09 12:57 UTC, jgpruitt approved these changes

2021-08-10 06:16 UTC, antekresic commented
bors r+

2021-08-10 06:26 UTC, merged