Added SQL command to get current default retention period
timescale/promscale pull request #737
Opened 2021-09-08 17:01 UTC by nmaludy

Added SQL a command to the docs for getting the default metric retention period. This is useful for idempotency checks in config management tools like Puppet, Ansible, etc.

2021-09-08 17:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/timescale/promscale?pullRequest=737) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/timescale/promscale?pullRequest=737) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/timescale/promscale?pullRequest=737) it.</sub>

2021-09-13 04:28 UTC, Harkishen-Singh requested changes
Thank you for the PR. Can you also add one for fetching retention period specific to a metric, since we support different individual metric retention periods?

2021-09-13 04:28 UTC, Harkishen-Singh commented on docs/metric_deletion_and_retention.md
Can you also add SQL command to get retention period for a specific metric?

```postgresql
SELECT EXTRACT(day FROM _prom_catalog.get_metric_retention_period('<metric_name>'))
```

2022-01-03 13:06 UTC, nmaludy commented
@VineethReddy02 done

2022-01-03 16:52 UTC, bitwalker commented on docs/metric_deletion_and_retention.md
> +SELECT EXTRACT(day FROM _prom_catalog.get_metric_retention_period(container_cpu_usage_seconds_total')) AS retention_days;
```suggestion
SELECT EXTRACT(day FROM _prom_catalog.get_metric_retention_period('container_cpu_usage_seconds_total')) AS retention_days;
```

2022-01-03 16:54 UTC, bitwalker approved these changes
LGTM! Just one small typo

2022-01-03 17:02 UTC, bitwalker approved these changes

2022-01-06 05:27 UTC, Harkishen-Singh approved these changes

2022-01-06 05:27 UTC, merged